### ISSUE TITLE
Metrics issue in oneops

### ISSUE THREAD

**Issue by yrmallu** [oneops/oo-commons#33]
@sureshg @gauravlall @okornev @khushbulohia 
-----error----
HTTP Post (1.5ms)  http://search:9200/cost/ci/_search
Failed to fetch 'cost' for nsPath=/devinstance/testassembly, date range=[2017-05-01, 2017-05-03: Failed.  Response code = 404.  Response message = Not Found.
  HTTP Post (6.8ms)  http://search:9200/cms-all/ci/_search
Failed to fetch 'cost_rate' for nsPath /devinstance/testassembly*bom/*: Failed.  Response code = 500.  Response message = Internal Server Error.
  HTTP Post (2.4ms)  http://search:9200/cost-*/ci/_search
Failed to fetch 'cost_time_histogram' for nsPath=/devinstance/testassembly, date range=[2017-03-01, 2017-05-03], interval=month: undefined method `[]' for nil:NilClass

------2nd error------

HTTP Post (1.1ms)  http://sensor:8080/sensor/rest/ops/states
Failed to retrieve instances operations states: Failed.  Response code = 404.  Response message = Not Found.

**Comment by mosabua** [comment]
Issue tracking is migrated to Walmart JIRA and https://github.com/oneops/oneops.
